services:
  admin:
    container_name: foodhub-admin
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/home/node/app
    environment:
      - VITE_API_URL=http://nginx/api/v1
      - VITE_WS_URL=http://soketi:6001
      - VITE_APP_NAME=FoodHub Admin
      - VITE_PUSHER_APP_KEY=app-key
      - VITE_PUSHER_HOST=soketi
      - VITE_PUSHER_PORT=6001
      - VITE_PUSHER_SCHEME=ws
    networks:
      - foodhub-network

networks:
  foodhub-network:
    external: true
    name: foodhub_foodhub-network

